# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  # the JDBC URL
  url: jdbc:h2:./target/example;AUTO_SERVER=TRUE
#  url: jdbc:h2:tcp://localhost:8082/nio:./target/example

server:
  type: simple
  connector:
    type: http
    port: 3002
  applicationContextPath: /

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.sunnepah: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console

clientSecrets:
    facebook: 298fb6c080fda239b809ae418bf49700
    google: xGxxgKAObIRUwOKycySkL9Fi
    linkedin: Linkedin Client Secret
    github: Github Client Secret
    foursquare: Foursquare Secret
    twitter: Twitter Consumer Key


mongo:
  seeds:
  - host: localhost
    port: 27017
  database: savewithme